routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('login',[\App\Http\Controllers\LoginController::class,'login'])->name('login.post');
Route::get('login',[\App\Http\Controllers\LoginController::class,'index'])->name('login');


Route::middleware([\App\Http\Middleware\Authenticate::class])->group(function (){
Route::get('/',[\App\Http\Controllers\ProductController::class,'index']);
Route::get('profile/{id}',[\App\Http\Controllers\UserController::class,'profile'])->name('user.profile');
Route::PUT('profile-update',[\App\Http\Controllers\UserController::class,'profileUpdate'])->name('user.profile-update');
Route::get('logout',[\App\Http\Controllers\UserController::class,'logout'])->name('user.logout');
Route::delete('product-file-delete/{id}',[\App\Http\Controllers\ProductController::class,'deleteFile'])->name('product.file-delete');
Route::resource('product',\App\Http\Controllers\ProductController::class);
Route::resource('user',\App\Http\Controllers\UserController::class);
Route::resource('use-area',\App\Http\Controllers\UseAreaController::class);
Route::resource('use-area-type',\App\Http\Controllers\UseAreaTypeController::class);
Route::resource('use-product',\App\Http\Controllers\UseProductController::class);
Route::resource('manufacturer',\App\Http\Controllers\ManufacturerControler::class);
Route::resource('tag',\App\Http\Controllers\TagController::class);
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    protected $guarded = [];

    public static function booted()
    {
        static::deleting(function ($product) {
            $dataCheck = $product->pivot()->get();
            if ($dataCheck->isNotEmpty()) {
                dd('It cannot be deleted because there is other data that has a dependency on the data you want to delete.');
            }
        });
    }

    public function tag(){
        return $this->belongsToMany(Tag::class);
    }

    public function useArea(){
        return $this->belongsToMany(UseArea::class)->withPivot('user_id','quantity','date','action');
    }

    public function manufacturer(){
        return $this->belongsTo(Manufacturer::class);
    }

    public function remainingQuantity(){
        $useProductSupplied = ProductUseArea::where('product_id',$this->id)->where('action',1)->sum('quantity');
        $useProductReceived = ProductUseArea::where('product_id',$this->id)->where('action',0)->sum('quantity');
        $result = intval($useProductSupplied) - intval($useProductReceived);
        return $result;
    }

    public function pivot(){
        return $this->hasMany(ProductUseArea::class);
    }

    public function files(){
        return $this->hasMany(ProductFile::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Manufacturer;
use App\Models\Product;
use App\Models\ProductFile;
use App\Models\Tag;
use App\Models\UseArea;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ProductController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $products = Product::query();

        if($request->filled('use_area_id')){
            $products = $products->whereHas('pivot',function ($query) use($request){
               return $query->where('use_area_id',$request->use_area_id);
            });
        }

        if ($request->filled('manufacturer_id')){
            $products = $products->where('manufacturer_id',$request->manufacturer_id);
        }

        if ($request->filled('name')){
            $products = $products->where('name','like','%'.$request->name.'%');
        }


        if ($request->filled('tag_ids')){
            foreach ($request->tag_ids as $tag){
                $products = $products->whereHas('tag',function ($query) use($tag){
                    return $query->where('tag_id',$tag);
                });
            }
        }

        $products = $products->orderByDesc('id')->paginate(30);


        $useAreas = UseArea::all();
        $manufacturers = Manufacturer::all();
        $tags = Tag::all();
        return view('Product.index',compact('products','useAreas','manufacturers','tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $manufacturers = Manufacturer::all();
        $tags = Tag::all();
        return view('Product.create',compact('manufacturers','tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $image = null;

        if ($request->hasFile('image')) {

            $uploadedFile = $request->file('image');

            $image = time() . $uploadedFile->getClientOriginalName();
            Storage::disk('product_images')->putFileAs(
                '',
                $uploadedFile,
                $image
            );
        }

        $data = Product::create($request->except(['image', 'tags']));
        $data->image = $image;
        $data->save();

        $status = $data ? 200 : 500;

        if ($request->filled('tags')){
        foreach ($request->tags as $tag) {
            $data->tag()->attach($tag, [
                'created_at' => date('Y-m-d H:i:s')
            ]);
        }
        }

        return redirect(route('product.index'))->with('status', $status);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Product::find($id);
        $data->remaining = $data->quantity - abs($data->remainingQuantity());
        $manufacturers = Manufacturer::all();
        $tags = Tag::all();
        $productTags = $data->tag->pluck('id');
        $productTags = $productTags->toArray();
        return view('Product.edit',compact('data','manufacturers','tags','productTags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $product = Product::find($id);
        if ($request->hasFile('file')){
            $request->validate([
                'file_name' => 'required'
            ]);
            $uploadedFile = $request->file('file');

            $filename = time().$uploadedFile->getClientOriginalName();
            Storage::disk('public_uploads')->putFileAs(
               '',
                $uploadedFile,
                $filename
            );

            ProductFile::create([
                'name' => $request->file_name,
                'product_id' => $product->id,
                'path' => '/files/'.$filename
            ]);
        }

        $image = $request->old_image;
        if ($request->hasFile('image')){

            $uploadedFile = $request->file('image');

            $image = time().$uploadedFile->getClientOriginalName();
            Storage::disk('product_images')->putFileAs(
                '',
                $uploadedFile,
                $image
            );
            Storage::disk('product_images')->delete($request->old_image);
        }

        $product->tag()->detach();
        foreach ($request->tags as $tag){
            $product->tag()->attach($tag,[
                'created_at' => date('Y-m-d H:i:s')
            ]);
        }

       $status = $product->update([
            'name' => $request->name,
            'part_code' => $request->part_code,
            'web_site' => $request->web_site,
            'quantity' => $request->quantity,
            'note' => $request->note,
            'image' => $image,
            'manufacturer_id' => $request->manufacturer_id
        ]);

        $status = $product ? 200 : 500;
        return  redirect(route('product.edit',$id))->with('status',$status);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Product::find($id)->delete();
        $status = $data ? 200 : 500;
        return  redirect(route('product.index'))->with('status',$status);
    }

    public function deleteFile($id){
        $file = ProductFile::find($id);
        Storage::disk('public_uploads')->delete('/files/'.$file->path);
        $file->delete();
        return back()->with('status','200');
    }
}

resources/views/Product/create.blade.php
@extends('layout')
@section('content')
    <div class="container-fluid">
        <header class="section-header">
            <div class="tbl">
                <div class="tbl-row">
                    <div class="tbl-cell">
                        <h3>Product Add</h3>
                    </div>
                </div>
            </div>
        </header>
        <div class="box-typical box-typical-padding">
            <form action="{{route('product.store')}}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Name</label>
                            <input type="text" class="form-control" name="name" value="" required maxlength="500">
                        </fieldset>
                    </div>
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Part Code</label>
                            <input type="text" class="form-control" name="part_code" value="" maxlength="300">
                        </fieldset>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Web Site</label>
                            <input type="text" class="form-control" name="web_site" value="" maxlength="255">
                        </fieldset>
                    </div>
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Quantity</label>
                            <input type="text" class="form-control" name="quantity" value="0" required>
                        </fieldset>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Manufacturer</label>
                            <select name="manufacturer_id" class="form-control">
                                <option value="">-</option>
                                @foreach($manufacturers as $manufacturer)
                                    <option value="{{$manufacturer->id}}">{{$manufacturer->name}}</option>
                                @endforeach
                            </select>
                        </fieldset>
                    </div>
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Product Image</label>
                            <input type="file" class="form-control" name="image" value="0" accept="image/*">
                        </fieldset>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <label class="form-label semibold">Tags</label>
                        <select class="select2" name="tags[]" multiple="multiple">
                            @foreach($tags as $tag)
                                <option value="{{$tag->id}}">{{$tag->name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <label class="form-label semibold">Note</label>
                        <textarea class="form-control" name="note"></textarea>
                    </div>
                </div>




                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-6 float-right">
                            <button type="submit" class="btn btn-success float-right"><i class="fa fa-save"></i> Save</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/Product/edit.blade.php
@extends('layout')
@section('content')
    <div class="container-fluid">
        <header class="section-header">
            <div class="tbl">
                <div class="tbl-row">
                    <div class="tbl-cell">
                        <h3>Product Edit</h3>
                        <div class="float-right">
                            <img src="/product_images/{{$data->image}}" width="159">
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <div class="box-typical box-typical-padding">
            <form action="{{route('product.update',$data->id)}}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <input type="hidden" name="old_image" value="{{$data->image}}">
                <div class="row">
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Name</label>
                            <input type="text" class="form-control" name="name" value="{{$data->name}}" required maxlength="500">
                        </fieldset>
                    </div>
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Part Code</label>
                            <input type="text" class="form-control" name="part_code" value="{{$data->part_code}}" maxlength="300">
                        </fieldset>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Web Site</label>
                            <input type="text" class="form-control" name="web_site" value="{{$data->web_site}}" maxlength="255">
                        </fieldset>
                    </div>
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Quantity</label>
                            <input type="text" class="form-control" name="quantity" value="{{$data->quantity}}" required>
                        </fieldset>
                    </div>

                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Net Quantity</label>
                            <input type="text" class="form-control" value="{{$data->remaining}}" disabled>
                        </fieldset>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Manufacturer</label>
                            <select name="manufacturer_id" class="form-control">
                                <option value="">-</option>
                                @foreach($manufacturers as $manufacturer)
                                    <option value="{{$manufacturer->id}}" {{$data->manufacturer_id == $manufacturer->id ? 'selected' : ''}}>{{$manufacturer->name}}</option>
                                @endforeach
                            </select>
                        </fieldset>
                    </div>
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Product Image</label>
                            <input type="file" class="form-control" name="image" value="0" accept="image/*">
                        </fieldset>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">File Name</label>
                            <input type="text" class="form-control" name="file_name">
                        </fieldset>
                    </div>
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">File</label>
                            <input type="file" class="form-control" name="file">
                        </fieldset>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <label class="form-label semibold">Tags</label>
                        <select class="select2" name="tags[]" multiple="multiple">
                            @foreach($tags as $tag)
                            <option value="{{$tag->id}}" {{ in_array($tag->id,$productTags) ? 'selected' : ''}}>{{$tag->name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12">
                        <label class="form-label semibold">Note</label>
                        <textarea class="form-control" name="note">{{$data->note}}</textarea>
                    </div>
                </div>


                <div class="row mt-2">
                    <div class="col-md-12">
                        <div class="col-md-6 float-right">
                            <button type="submit" class="btn btn-success float-right"><i class="fa fa-save"></i> Save</button>
                        </div>
                    </div>
                </div>
            </form>

        </div>

        <hr>
        <div class="row">
            <table id="table-sm" class="table table-bordered table-hover table-sm">
                <thead>
                <tr>
                    <th class="text-center">Created Date</th>
                    <th class="text-center">Name</th>
                    <th class="text-center">Filename</th>
                    <th class="text-center">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($data->files as $value)
                <tr>
                    <td class="text-center">{{date('d.m.Y',strtotime($value->created_at))}}</td>
                    <td class="text-center">{{$value->name}}</td>
                    <td class="text-center">{{$value->path}}</td>
                    <td class="text-center">
                        <div class="">
                            <a target="_blank" href="{{$value->path}}"><button type="button" class="btn btn-primary btn-sm"><i class="fa fa-eye"></i> Show PDF</button></a>
                            <form action="{{route('product.file-delete',$value->id)}}" method="POST">@csrf @method('delete')<button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o"></i> Delete</button></form>
                        </div>
                    </td>
                </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <hr>
        <div class="row">
            <h3>Received Product</h3>
            <table id="table-sm" class="table table-bordered table-hover table-sm">
                <thead>
                <tr>
                    <th class="text-center">Created At</th>
                    <th class="text-center">Created Name</th>
                    <th class="text-center">Use Area Name</th>
                    <th class="text-center">Process</th>
                    <th class="text-center">Quantity</th>
                    <th class="text-center">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($data->pivot as $value)
                    @if(!$value->action)
                    <tr>
                        <td class="text-center">{{date('d.m.Y',strtotime($value->created_at))}}</td>
                        <td class="text-center">{{$value->product->name}}</td>
                        <td class="text-center">{{$value->useArea->name}}</td>
                        <td class="text-center">{{$value->action ? 'Supplied product' : 'Received product'}}</td>
                        <td class="text-center">{{$value->quantity}}</td>
                        <td class="text-center">
                            <div class="">
                                <a href="{{route('use-product.edit',$value->id)}}"><button type="button" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i> Show</button></a>
                            </div>
                        </td>
                    </tr>
                    @endif
                @endforeach
                </tbody>
            </table>
        </div>

        <hr>
        <div class="row">
        <h3>Supplied Product</h3>
            <table id="table-sm" class="table table-bordered table-hover table-sm">
                <thead>
                <tr>
                    <th class="text-center">Created At</th>
                    <th class="text-center">Created Name</th>
                    <th class="text-center">Use Area Name</th>
                    <th class="text-center">Process</th>
                    <th class="text-center">Quantity</th>
                    <th class="text-center">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($data->pivot as $value)
                    @if($value->action)

                        <tr>
                        <td class="text-center">{{date('d.m.Y',strtotime($value->created_at))}}</td>
                        <td class="text-center">{{$value->product->name}}</td>
                        <td class="text-center">{{$value->useArea->name}}</td>
                        <td class="text-center">{{$value->action ? 'Supplied product' : 'Received product'}}</td>
                        <td class="text-center">{{$value->quantity}}</td>
                        <td class="text-center">
                            <div class="">
                                <a href="{{route('use-product.edit',$value->id)}}"><button type="button" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i> Show</button></a>
                            </div>
                        </td>
                    </tr>
                        @endif
                @endforeach
                </tbody>
            </table>
        </div>

    </div>
@endsection

resources/views/Product/index.blade.php
@extends('layout')
@section('content')
    <div class="container-fluid">
        <header class="section-header">
            <div class="tbl">
                <div class="tbl-row">
                    <div class="tbl-cell">
                        <h3>Productssssssss</h3>
                    </div>
                    <div class="float-right">
                        <a href="{{route('product.create')}}"> <button type="button" class="btn btn-warning"><i class="fa fa-plus"></i> Product Add</button></a>
                    </div>
                </div>
            </div>
        </header>
        <div class="box-typical box-typical-padding">
            <form action="{{route('product.index')}}" method="GET">
            <div class="row">
                <div class="col-md-2">
                    <fieldset class="form-group">
                        <label class="form-label semibold">Use Area</label>
                        <select name="use_area_id" class="form-control">
                            <option value="">All</option>
                            @foreach($useAreas as $useArea)
                                <option value="{{$useArea->id}}" {{\Illuminate\Support\Facades\Request::get('use_area_id') ? 'selected' : '' }}>{{$useArea->name}}</option>
                            @endforeach
                        </select>
                    </fieldset>
                </div>

                <div class="col-md-2">
                    <fieldset class="form-group">
                        <label class="form-label semibold">Product Name</label>
                       <input type="text" class="form-control" name="name" value="{{\Illuminate\Support\Facades\Request::get('name') }}">
                    </fieldset>
                </div>

                <div class="col-md-2">
                    <fieldset class="form-group">
                        <label class="form-label semibold">Manufacturer</label>
                        <select name="manufacturer_id" class="form-control">
                            <option value="">All</option>
                            @foreach($manufacturers as $manufacturer)
                                <option value="{{$manufacturer->id}}" {{\Illuminate\Support\Facades\Request::get('manufacturer_id') ? 'selected' : '' }}>{{$manufacturer->name}}</option>
                            @endforeach
                        </select>
                    </fieldset>
                </div>

                <div class="col-md-2">
                    <fieldset class="form-group">
                        <label class="form-label semibold">Tag</label>
                        <select name="tag_ids[]" class="select2" multiple>
                            @foreach($tags as $tag)
                                <option value="{{$tag->id}}" {{ !is_null(\Illuminate\Support\Facades\Request::get('tag_ids')) ? (in_array($tag->id,\Illuminate\Support\Facades\Request::get('tag_ids')) ? 'selected' : '') : ''}}>{{$tag->name}}</option>
                            @endforeach
                        </select>
                    </fieldset>
                </div>

                <div class="col-md-2 align-self-center">
                    <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i></button>
                </div>
            </div>
            </form>

            <table id="table-sm" class="table table-bordered table-hover table-sm">
                <thead>
                <tr>
                    <th class="text-center" width="1">#</th>
                    <th class="text-center">Image</th>
                    <th class="text-center">Manufacturer</th>
                    <th class="text-center">Name</th>
                    <th class="text-center">Part Code</th>
                    <th class="text-center">Quantity</th>
                    <th class="text-center">Web Site</th>
                    <th class="text-center">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($products as $value)
                    <tr>
                        <td class="text-center">{{$value->id}}</td>
                        <td class="text-center">@if($value->image)<img src="{{'/product_images/'.$value->image}}" width="150">@else - @endif </td>
                        <td class="text-center"> {{!empty($value->manufacturer_id) ? $value->manufacturer->name : '-'}}</td>
                        <td class="text-center">{{$value->name}}</td>
                        <td class="text-center">{{$value->part_code}}</td>
                        <td class="text-center">{{$value->quantity}}</td>
                        <td class="text-center">{{$value->web_site}}</td>
                        <td class="text-center" width="250">
                            <div class="row">
                                <div class="col-md-6">
                                    <a href="{{route('product.edit',$value->id)}}"><button type="button" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i> Edit</button></a>
                                </div>
                                @if(\Illuminate\Support\Facades\Auth::user()->delete_permission)
                                <div class="col-md-6">
                                    <form action="{{route('product.destroy',$value->id)}}" method="POST">@csrf @method('delete')<button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o"></i> Delete</button></form>
                                </div>
                                    @endif
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>


                <div class="d-flex justify-content-center">
                    {{ $products->appends(request()->input())->links() }}

                </div>

        </div>


    </div>
@endsection