routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('login',[\App\Http\Controllers\LoginController::class,'login'])->name('login.post');
Route::get('login',[\App\Http\Controllers\LoginController::class,'index'])->name('login');


Route::middleware([\App\Http\Middleware\Authenticate::class])->group(function (){
Route::get('/',[\App\Http\Controllers\ProductController::class,'index']);
Route::get('profile/{id}',[\App\Http\Controllers\UserController::class,'profile'])->name('user.profile');
Route::PUT('profile-update',[\App\Http\Controllers\UserController::class,'profileUpdate'])->name('user.profile-update');
Route::get('logout',[\App\Http\Controllers\UserController::class,'logout'])->name('user.logout');
Route::delete('product-file-delete/{id}',[\App\Http\Controllers\ProductController::class,'deleteFile'])->name('product.file-delete');
Route::resource('product',\App\Http\Controllers\ProductController::class);
Route::resource('user',\App\Http\Controllers\UserController::class);
Route::resource('use-area',\App\Http\Controllers\UseAreaController::class);
Route::resource('use-area-type',\App\Http\Controllers\UseAreaTypeController::class);
Route::resource('use-product',\App\Http\Controllers\UseProductController::class);
Route::resource('manufacturer',\App\Http\Controllers\ManufacturerControler::class);
Route::resource('tag',\App\Http\Controllers\TagController::class);
});

app/Models/Manufacturer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Manufacturer extends Model
{
    use HasFactory;
    protected $fillable = ['name'];

    public static function booted() {
        static::deleting(function ($manufacturer) {
            $dataCheck = $manufacturer->product()->get();
            if ($dataCheck->isNotEmpty()) {
                dd('It cannot be deleted because there is other data that has a dependency on the data you want to delete.');
            }
        });
    }

    public function product(){
        return $this->hasMany(Product::class);
    }
}

resources/views/Manufacturer/create.blade.php
@extends('layout')
@section('content')
    <div class="container-fluid">
        <header class="section-header">
            <div class="tbl">
                <div class="tbl-row">
                    <div class="tbl-cell">
                        <h3>Manufacturer Add</h3>
                    </div>
                </div>
            </div>
        </header>
        <div class="box-typical box-typical-padding">
            <form action="{{route('manufacturer.store')}}" method="POST">
                @csrf
                <div class="row">
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Name</label>
                            <input type="text" class="form-control" name="name" value="" required maxlength="255">
                        </fieldset>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-6 float-right">
                            <button type="submit" class="btn btn-success float-right"><i class="fa fa-save"></i> Save</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/Manufacturer/edit.blade.php
@extends('layout')
@section('content')
    <div class="container-fluid">
        <header class="section-header">
            <div class="tbl">
                <div class="tbl-row">
                    <div class="tbl-cell">
                        <h3>Manufacturer Edit</h3>
                    </div>
                </div>
            </div>
        </header>
        <div class="box-typical box-typical-padding">
            <form action="{{route('manufacturer.update',$manufacturer->id)}}" method="POST">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Name</label>
                            <input type="text" class="form-control" name="name" value="{{$manufacturer->name}}" required maxlength="255">
                        </fieldset>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-6 float-right">
                            <button type="submit" class="btn btn-success float-right"><i class="fa fa-save"></i> Save</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/Manufacturer/index.blade.php
@extends('layout')
@section('content')
    <div class="container-fluid">
        <header class="section-header">
            <div class="tbl">
                <div class="tbl-row">
                    <div class="tbl-cell">
                        <h3>Manufacturer</h3>
                    </div>
                    <div class="float-right">
                        <a href="{{route('manufacturer.create')}}"> <button type="button" class="btn btn-warning"><i class="fa fa-plus"></i> Manufacturer Add</button></a>
                    </div>
                </div>
            </div>
        </header>
        <div class="box-typical box-typical-padding">
            <table id="table-sm" class="table table-bordered table-hover table-sm">
                <thead>
                <tr>
                    <th class="text-center" width="1">#</th>
                    <th class="text-center">Name</th>
                    <th class="text-center">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($manufacturers as $value)
                    <tr>
                        <td class="text-center">{{$value->id}}</td>
                        <td class="text-center">{{$value->name}}</td>
                        <td class="text-center">
                            <div class="">
                                <a href="{{route('manufacturer.edit',$value->id)}}"><button type="button" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i> Edit</button></a>
                                @if(\Illuminate\Support\Facades\Auth::user()->delete_permission)
                                    <form action="{{route('manufacturer.destroy',$value->id)}}" method="POST">@csrf @method('delete')<button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o"></i> Delete</button></form>
                                @endif
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection