routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('login',[\App\Http\Controllers\LoginController::class,'login'])->name('login.post');
Route::get('login',[\App\Http\Controllers\LoginController::class,'index'])->name('login');


Route::middleware([\App\Http\Middleware\Authenticate::class])->group(function (){
Route::get('/',[\App\Http\Controllers\ProductController::class,'index']);
Route::get('profile/{id}',[\App\Http\Controllers\UserController::class,'profile'])->name('user.profile');
Route::PUT('profile-update',[\App\Http\Controllers\UserController::class,'profileUpdate'])->name('user.profile-update');
Route::get('logout',[\App\Http\Controllers\UserController::class,'logout'])->name('user.logout');
Route::delete('product-file-delete/{id}',[\App\Http\Controllers\ProductController::class,'deleteFile'])->name('product.file-delete');
Route::resource('product',\App\Http\Controllers\ProductController::class);
Route::resource('user',\App\Http\Controllers\UserController::class);
Route::resource('use-area',\App\Http\Controllers\UseAreaController::class);
Route::resource('use-area-type',\App\Http\Controllers\UseAreaTypeController::class);
Route::resource('use-product',\App\Http\Controllers\UseProductController::class);
Route::resource('manufacturer',\App\Http\Controllers\ManufacturerControler::class);
Route::resource('tag',\App\Http\Controllers\TagController::class);
});

app/Http/Controllers/UseProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\ProductUseArea;
use App\Models\UseArea;
use App\Models\User;
use Illuminate\Http\Request;

class UseProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $useProducts = ProductUseArea::with(['product','useArea'])->paginate(30);
        return  view('UseProduct.index',compact('useProducts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $useAreas = UseArea::all();
        $products = Product::all();
        $users = User::all();
        return view('UseProduct.create',compact('useAreas','products','users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $product = Product::find($request->product_id);
        $product->useArea()->attach($request->use_area_id,[
               'quantity' => $request->quantity,
                'date' => $request->date,
                'action' => $request->action,
                'user_id' => $request->user_id,
                'created_at' => date('Y-m-d H:i:s')
           ]);
        $status = 200;
        return redirect(route('use-product.index'))->with('status',$status);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = ProductUseArea::find($id);
        $useAreas = UseArea::all();
        $products = Product::all();
        $users = User::all();
        return view('UseProduct.edit',compact('data','products','useAreas','users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = ProductUseArea::find($id)->update([
            'product_id' => $request->product_id,
            'use_area_id' => $request->use_area_id,
            'user_id' => $request->user_id,
            'date' => $request->date,
            'action' => $request->action,
            'quantity' => $request->quantity
        ]);

        $status = $data ? 200 : 500;
        return  redirect(route('use-product.edit',$id))->with('status',$status);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = ProductUseArea::find($id)->delete();
        $status = $data ? 200 : 500;
        return  redirect(route('use-product.index'))->with('status',$status);
    }
}

resources/views/UseProduct/create.blade.php
@extends('layout')
@section('content')
    <div class="container-fluid">
        <header class="section-header">
            <div class="tbl">
                <div class="tbl-row">
                    <div class="tbl-cell">
                        <h3>Use Product</h3>
                    </div>
                </div>
            </div>
        </header>
        <div class="box-typical box-typical-padding">
            <form action="{{route('use-product.store')}}" method="POST">
                @csrf
                <div class="row">
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Product</label>
                            <select name="product_id" class="form-control" required>
                                <option value=""></option>
                                @foreach($products as $product)
                                    <option value="{{$product->id}}">{{$product->name}}</option>
                                @endforeach
                            </select>
                        </fieldset>
                    </div>
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Use Area</label>
                            <select name="use_area_id" class="form-control" required>
                                <option value=""></option>
                                @foreach($useAreas as $useArea)
                                    <option value="{{$useArea->id}}">{{$useArea->name}}</option>
                                @endforeach
                            </select>
                        </fieldset>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Quantity</label>
                            <input type="number" class="form-control" name="quantity" value="" required>
                        </fieldset>
                    </div>

                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">User</label>
                            <select name="user_id" class="form-control" required>
                                <option value=""></option>
                                @foreach($users as $user)
                                    <option value="{{$user->id}}">{{$user->name}}</option>
                                @endforeach
                            </select>
                        </fieldset>
                    </div>

                </div>

                <div class="row">
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Date</label>
                            <input type="date" class="form-control" name="date" value="{{date('Y-m-d')}}" required>
                        </fieldset>
                    </div>

                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Process</label>
                            <select name="action" class="form-control" required>
                                <option value=""></option>
                                <option value="1">Supplied product</option>
                                <option value="0">Received product</option>
                            </select>
                        </fieldset>
                    </div>


                </div>


                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-6 float-right">
                            <button type="submit" class="btn btn-success float-right"><i class="fa fa-save"></i> Save</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/UseProduct/edit.blade.php
@extends('layout')
@section('content')
    <div class="container-fluid">
        <header class="section-header">
            <div class="tbl">
                <div class="tbl-row">
                    <div class="tbl-cell">
                        <h3>Use Product</h3>
                    </div>

                </div>
            </div>
        </header>
        <div class="box-typical box-typical-padding">
            <form action="{{route('use-product.update',$data->id)}}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="row">
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Product</label>
                            <select name="product_id" class="form-control" required>
                                <option value=""></option>
                                @foreach($products as $product)
                                    <option value="{{$product->id}}" {{$product->id == $data->product_id ? 'selected' : ''}}>{{$product->name}}</option>
                                @endforeach
                            </select>
                        </fieldset>
                    </div>
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Use Area</label>
                            <select name="use_area_id" class="form-control" required>
                                <option value=""></option>
                                @foreach($useAreas as $useArea)
                                    <option value="{{$useArea->id}}" {{$useArea->id == $data->use_area_id ? 'selected' : ''}}>{{$useArea->name}}</option>
                                @endforeach
                            </select>
                        </fieldset>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Quantity</label>
                            <input type="number" class="form-control" name="quantity" value="{{$data->quantity}}" required>
                        </fieldset>
                    </div>

                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">User</label>
                            <select name="user_id" class="form-control" required>
                                <option value=""></option>
                                @foreach($users as $user)
                                    <option value="{{$user->id}}" {{$user->id == $data->user_id ? 'selected' : ''}}>{{$user->name}}</option>
                                @endforeach
                            </select>
                        </fieldset>
                    </div>

                </div>

                <div class="row">
                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Date</label>
                            <input type="date" class="form-control" name="date" value="{{$data->date}}" required>
                        </fieldset>
                    </div>

                    <div class="col-md-6">
                        <fieldset class="form-group">
                            <label class="form-label semibold">Process</label>
                            <select name="action" class="form-control" required>
                                <option value=""></option>
                                <option value="1" {{$data->action == 1 ? 'selected' : ''}}>Supplied product</option>
                                <option value="0" {{$data->action == 0 ? 'selected' : ''}}>Received product</option>
                            </select>
                        </fieldset>
                    </div>


                </div>


                <div class="row">
                    <div class="col-md-12">
                        <div class="col-md-6 float-right">
                            <button type="submit" class="btn btn-success float-right"><i class="fa fa-save"></i> Save</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/UseProduct/index.blade.php
@extends('layout')
@section('content')
    <div class="container-fluid">
        <header class="section-header">
            <div class="tbl">
                <div class="tbl-row">
                    <div class="tbl-cell">
                        <h3>Use Product</h3>
                    </div>
                    <div class="float-right">
                        <a href="{{route('use-product.create')}}"> <button type="button" class="btn btn-warning"><i class="fa fa-plus"></i> Use Product</button></a>
                    </div>
                </div>
            </div>
        </header>
        <div class="box-typical box-typical-padding">

            <table id="table-sm" class="table table-bordered table-hover table-sm">
                <thead>
                <tr>
                    <th class="text-center" width="1">#</th>
                    <th class="text-center">Name</th>
                    <th class="text-center">Use Area Name</th>
                    <th class="text-center">Process</th>
                    <th class="text-center">Quantity</th>
                    <th class="text-center">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($useProducts as $value)
                    <tr>
                        <td class="text-center">{{$value->id}}</td>
                        <td class="text-center">{{$value->product->name}}</td>
                        <td class="text-center">{{$value->useArea->name}}</td>
                        <td class="text-center">{{$value->action ? 'Supplied product' : 'Received product'}}</td>
                        <td class="text-center">{{$value->quantity}}</td>
                        <td class="text-center">
                            <div class="">
                                <a href="{{route('use-product.edit',$value->id)}}"><button type="button" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i> Edit</button></a>
                                @if(\Illuminate\Support\Facades\Auth::user()->delete_permission)
                                <form action="{{route('use-product.destroy',$value->id)}}" method="POST">@csrf @method('delete')<button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o"></i> Delete</button></form>
                                @endif
                            </div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>


            <div class="d-flex justify-content-center">
                {!! $useProducts->links() !!}
            </div>

        </div>


    </div>
@endsection